# Generated by Django 3.1.4 on 2021-01-03 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201209_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'rar'])]),
        ),
    ]
