# Generated by Django 3.1.5 on 2021-01-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nameu',
        ),
    ]
