# Generated by Django 3.1.5 on 2021-01-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210119_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
