# Generated by Django 3.1.4 on 2021-01-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='imgorder/', width_field='width_field'),
        ),
    ]
